# Generated by Django 3.1.7 on 2019-12-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191211_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
