# Generated by Django 3.1.7 on 2019-12-14 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20191213_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='borrower',
            field=models.ForeignKey(blank=True, default='Not loaned', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='due_back',
            field=models.DateField(blank=True, default='Not loaned', null=True),
        ),
    ]
